# Supabase CLI configuration
# Created by create-supabase-app

project_id = "mwfwnjztrqseoqzoycsc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
external_email_enabled = true
external_phone_enabled = true
external_apple_enabled = false
external_azure_enabled = false
external_bitbucket_enabled = false
external_discord_enabled = false
external_facebook_enabled = false
external_github_enabled = false
external_gitlab_enabled = false
external_google_enabled = false
external_keycloak_enabled = false
external_linkedin_enabled = false
external_notion_enabled = false
external_twitch_enabled = false
external_twitter_enabled = false
external_slack_enabled = false
external_spotify_enabled = false
external_workos_enabled = false
external_zoom_enabled = false

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[functions]
verify_jwt = true
